"use strict";
var __awaiter = (this && this.__awaiter) || function (thisArg, _arguments, P, generator) {
    function adopt(value) { return value instanceof P ? value : new P(function (resolve) { resolve(value); }); }
    return new (P || (P = Promise))(function (resolve, reject) {
        function fulfilled(value) { try { step(generator.next(value)); } catch (e) { reject(e); } }
        function rejected(value) { try { step(generator["throw"](value)); } catch (e) { reject(e); } }
        function step(result) { result.done ? resolve(result.value) : adopt(result.value).then(fulfilled, rejected); }
        step((generator = generator.apply(thisArg, _arguments || [])).next());
    });
};
var __generator = (this && this.__generator) || function (thisArg, body) {
    var _ = { label: 0, sent: function() { if (t[0] & 1) throw t[1]; return t[1]; }, trys: [], ops: [] }, f, y, t, g = Object.create((typeof Iterator === "function" ? Iterator : Object).prototype);
    return g.next = verb(0), g["throw"] = verb(1), g["return"] = verb(2), typeof Symbol === "function" && (g[Symbol.iterator] = function() { return this; }), g;
    function verb(n) { return function (v) { return step([n, v]); }; }
    function step(op) {
        if (f) throw new TypeError("Generator is already executing.");
        while (g && (g = 0, op[0] && (_ = 0)), _) try {
            if (f = 1, y && (t = op[0] & 2 ? y["return"] : op[0] ? y["throw"] || ((t = y["return"]) && t.call(y), 0) : y.next) && !(t = t.call(y, op[1])).done) return t;
            if (y = 0, t) op = [op[0] & 2, t.value];
            switch (op[0]) {
                case 0: case 1: t = op; break;
                case 4: _.label++; return { value: op[1], done: false };
                case 5: _.label++; y = op[1]; op = [0]; continue;
                case 7: op = _.ops.pop(); _.trys.pop(); continue;
                default:
                    if (!(t = _.trys, t = t.length > 0 && t[t.length - 1]) && (op[0] === 6 || op[0] === 2)) { _ = 0; continue; }
                    if (op[0] === 3 && (!t || (op[1] > t[0] && op[1] < t[3]))) { _.label = op[1]; break; }
                    if (op[0] === 6 && _.label < t[1]) { _.label = t[1]; t = op; break; }
                    if (t && _.label < t[2]) { _.label = t[2]; _.ops.push(op); break; }
                    if (t[2]) _.ops.pop();
                    _.trys.pop(); continue;
            }
            op = body.call(thisArg, _);
        } catch (e) { op = [6, e]; y = 0; } finally { f = t = 0; }
        if (op[0] & 5) throw op[1]; return { value: op[0] ? op[1] : void 0, done: true };
    }
};
Object.defineProperty(exports, "__esModule", { value: true });
// import express from "express";
// import * as bodyParser from "body-parser";
// import {
//   compileRootHash,
//   compileHashAddresses,
//   generateMerkleProof,
//   makeMerkelRootFromProof,
// } from "../services";
// import { PrismaClient } from "@prisma/client";
// import crypto from "crypto";
// import { ethers } from "hardhat";
var axios_1 = require("axios");
// import data from '../data.json'
// const prisma = new PrismaClient();
function main() {
    return __awaiter(this, void 0, void 0, function () {
        var startTime, t, requestId, u, stop;
        var _a, _b, _c, _d;
        return __generator(this, function (_e) {
            switch (_e.label) {
                case 0:
                    startTime = new Date();
                    return [4 /*yield*/, axios_1.default.post("http://localhost:3000/verify-trustanchor/0xA4899D35897033b927acFCf422bc745916139776")];
                case 1:
                    t = _e.sent();
                    console.log("t", Number((_a = t === null || t === void 0 ? void 0 : t.data) === null || _a === void 0 ? void 0 : _a.substr(((_b = t === null || t === void 0 ? void 0 : t.data) === null || _b === void 0 ? void 0 : _b.length) - 3)));
                    requestId = Number((_c = t === null || t === void 0 ? void 0 : t.data) === null || _c === void 0 ? void 0 : _c.substr(((_d = t === null || t === void 0 ? void 0 : t.data) === null || _d === void 0 ? void 0 : _d.length) - 3));
                    return [4 /*yield*/, axios_1.default.post("http://localhost:3001/verify/".concat(requestId), {
                            "holderWallet": "0xf39fd6e51aad88f6f4ce6ab8827279cfffb92266",
                            "issuerAddress": "0xC9a43158891282A2B1475592D5719c001986Aaec",
                            "data": {
                                "type": "Buffer",
                                "data": [
                                    67,
                                    130,
                                    206,
                                    248,
                                    150,
                                    76,
                                    197,
                                    18,
                                    196,
                                    168,
                                    59,
                                    102,
                                    169,
                                    98,
                                    135,
                                    217,
                                    95,
                                    44,
                                    220,
                                    24,
                                    28,
                                    50,
                                    129,
                                    178,
                                    243,
                                    138,
                                    243,
                                    3,
                                    115,
                                    39,
                                    239,
                                    120,
                                    217,
                                    73,
                                    129,
                                    24,
                                    165,
                                    159,
                                    91,
                                    214,
                                    224,
                                    254,
                                    122,
                                    102,
                                    178,
                                    223,
                                    54,
                                    173,
                                    125,
                                    41,
                                    111,
                                    94,
                                    110,
                                    203,
                                    120,
                                    55,
                                    253,
                                    247,
                                    42,
                                    145,
                                    218,
                                    184,
                                    182,
                                    216,
                                    69,
                                    22,
                                    69,
                                    25,
                                    111,
                                    45,
                                    107,
                                    248,
                                    43,
                                    104,
                                    121,
                                    229,
                                    177,
                                    204,
                                    98,
                                    168,
                                    185,
                                    118,
                                    1,
                                    74,
                                    3,
                                    251,
                                    228,
                                    4,
                                    18,
                                    140,
                                    212,
                                    56,
                                    206,
                                    66,
                                    139,
                                    58,
                                    209,
                                    24,
                                    52,
                                    118,
                                    83,
                                    138,
                                    111,
                                    236,
                                    136,
                                    158,
                                    161,
                                    123,
                                    165,
                                    53,
                                    177,
                                    1,
                                    8,
                                    148,
                                    141,
                                    229,
                                    218,
                                    184,
                                    211,
                                    49,
                                    253,
                                    199,
                                    164,
                                    207,
                                    65,
                                    239,
                                    156,
                                    39,
                                    22,
                                    140,
                                    236,
                                    23,
                                    47,
                                    117,
                                    247,
                                    18,
                                    62,
                                    29,
                                    103,
                                    19,
                                    136,
                                    0,
                                    242,
                                    197,
                                    44,
                                    104,
                                    98,
                                    50,
                                    169,
                                    195,
                                    204,
                                    127,
                                    251,
                                    93,
                                    200,
                                    194,
                                    102,
                                    161,
                                    112,
                                    70,
                                    37,
                                    179,
                                    34,
                                    244,
                                    89,
                                    139,
                                    9,
                                    163,
                                    11,
                                    97,
                                    46,
                                    204,
                                    198,
                                    206,
                                    177,
                                    117,
                                    81,
                                    76,
                                    212,
                                    30,
                                    108,
                                    9,
                                    77,
                                    27,
                                    202,
                                    93,
                                    63,
                                    115,
                                    150,
                                    237,
                                    203,
                                    87,
                                    151,
                                    157,
                                    144,
                                    180,
                                    46,
                                    218,
                                    253,
                                    144,
                                    25,
                                    38,
                                    140,
                                    148,
                                    108,
                                    122,
                                    115,
                                    188,
                                    239,
                                    144,
                                    128,
                                    161,
                                    115,
                                    157,
                                    200,
                                    62,
                                    183,
                                    185,
                                    215,
                                    7,
                                    208,
                                    107,
                                    209,
                                    13,
                                    238,
                                    98,
                                    8,
                                    194,
                                    199,
                                    171,
                                    64,
                                    41,
                                    30,
                                    34,
                                    172,
                                    92,
                                    16,
                                    44,
                                    124,
                                    115,
                                    24,
                                    124,
                                    222,
                                    183,
                                    188,
                                    34,
                                    86,
                                    88,
                                    191,
                                    117,
                                    163,
                                    149,
                                    74,
                                    209,
                                    91,
                                    58,
                                    218,
                                    35,
                                    230,
                                    50,
                                    51,
                                    235,
                                    98,
                                    103,
                                    48,
                                    204,
                                    187,
                                    134,
                                    91,
                                    213,
                                    186,
                                    224,
                                    28,
                                    201,
                                    114,
                                    6,
                                    65,
                                    34,
                                    42,
                                    122,
                                    8,
                                    217,
                                    249,
                                    105,
                                    175,
                                    187,
                                    205,
                                    53,
                                    230,
                                    6,
                                    61,
                                    192,
                                    225,
                                    35,
                                    206,
                                    45,
                                    116,
                                    120,
                                    50,
                                    138,
                                    32,
                                    35,
                                    75,
                                    205,
                                    194,
                                    87,
                                    58,
                                    20,
                                    233,
                                    250,
                                    146,
                                    79,
                                    222,
                                    165,
                                    15,
                                    33,
                                    229,
                                    204,
                                    55,
                                    68,
                                    133,
                                    39,
                                    12,
                                    225,
                                    10,
                                    3,
                                    195,
                                    230,
                                    110,
                                    77,
                                    8,
                                    25,
                                    83,
                                    210,
                                    246,
                                    180,
                                    222,
                                    123,
                                    189,
                                    87,
                                    221,
                                    201,
                                    187,
                                    203,
                                    162,
                                    22,
                                    188,
                                    59,
                                    91,
                                    3,
                                    170,
                                    225,
                                    24,
                                    32,
                                    212,
                                    195,
                                    12,
                                    212,
                                    7,
                                    219,
                                    185,
                                    172,
                                    120,
                                    166,
                                    63,
                                    249,
                                    198,
                                    236,
                                    194,
                                    68,
                                    27,
                                    201,
                                    208,
                                    114,
                                    103,
                                    243,
                                    7,
                                    40,
                                    152,
                                    185,
                                    132,
                                    149,
                                    14,
                                    53,
                                    144,
                                    128,
                                    103,
                                    224,
                                    113,
                                    97,
                                    232,
                                    80,
                                    146,
                                    222,
                                    250,
                                    168,
                                    109,
                                    19,
                                    209,
                                    214,
                                    161,
                                    36,
                                    116,
                                    219,
                                    55,
                                    139,
                                    136,
                                    17,
                                    106,
                                    255,
                                    203,
                                    225,
                                    168,
                                    96,
                                    8,
                                    134,
                                    237,
                                    92,
                                    28,
                                    191,
                                    179,
                                    59,
                                    166,
                                    207,
                                    103,
                                    132,
                                    110,
                                    28,
                                    207,
                                    20,
                                    62,
                                    214,
                                    16,
                                    119,
                                    2,
                                    145,
                                    233,
                                    172,
                                    227,
                                    202,
                                    9,
                                    88,
                                    42,
                                    15,
                                    177,
                                    253,
                                    16,
                                    65,
                                    91,
                                    192,
                                    82,
                                    172,
                                    67,
                                    141,
                                    42,
                                    39,
                                    64,
                                    87,
                                    9,
                                    208,
                                    178,
                                    188,
                                    26,
                                    169,
                                    230,
                                    16,
                                    0,
                                    37,
                                    9,
                                    1,
                                    19,
                                    140,
                                    38,
                                    149,
                                    237,
                                    155,
                                    198,
                                    207,
                                    137,
                                    21,
                                    3,
                                    111,
                                    145,
                                    19,
                                    56,
                                    99,
                                    239,
                                    60,
                                    46,
                                    41,
                                    5,
                                    236,
                                    59,
                                    86,
                                    14,
                                    74,
                                    115,
                                    19,
                                    187,
                                    50,
                                    17,
                                    158,
                                    225,
                                    7,
                                    48,
                                    90,
                                    123,
                                    25,
                                    217,
                                    53,
                                    3,
                                    62
                                ]
                            }
                        })];
                case 2:
                    u = _e.sent();
                    stop = new Date().getTime() - startTime.getTime();
                    console.log("stop", stop);
                    return [2 /*return*/];
            }
        });
    });
}
main();
