version: '3.7'
services:
  db:
    image: postgres:12
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: test
    ports:
      - '5432:5432'
    volumes:
      - ./volumes/db/:/var/lib/postgresql/data/
    restart: always
